# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20170628_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
    ]
