# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170628_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='counter',
        ),
        migrations.AddField(
            model_name='poke',
            name='pokers',
            field=models.ManyToManyField(related_name='pokers', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.User'),
        ),
    ]
