# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20170628_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='pokers',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='user',
        ),
        migrations.AddField(
            model_name='poke',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='poke',
            name='pokedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokedpokes', to='firstapp.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokerpokes', to='firstapp.User'),
        ),
    ]
