# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20170628_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='counter',
            new_name='pokecount',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='pokedby',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ManyToManyField(related_name='pokerpokes', to='firstapp.User'),
        ),
    ]
